# Generated by Django 3.0.9 on 2020-09-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200929_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers_number',
            field=models.IntegerField(default=0),
        ),
    ]
