# Generated by Django 3.0.9 on 2020-10-03 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_followers_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers_number',
            new_name='followers_count',
        ),
    ]
